package org.lime.system.execute;

import org.lime.system.tuple.*;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;

// Generated by JavaScript (c) Lime
public interface Action2<T0, T1> extends Action1<Tuple2<T0,T1>> {
    void invoke(T0 arg0, T1 arg1);
    @Override default void invoke(Tuple2<T0,T1> arg0) { invoke(arg0.val0, arg0.val1); }
    @Override default Object call(Object[] args) { invoke((T0)args[0], (T1)args[1]); return null; }
    static <T0, T1>Action2<T0, T1> of(Method method) {
        return Modifier.isStatic(method.getModifiers()) ?
                (val0, val1) -> Execute.invoke(method, null, new Object[] { val0, val1 }) :
                (val0, val1) -> Execute.invoke(method, val0, new Object[] { val1 });
    }
}