package org.lime.system.execute;

// Generated by JavaScript (c) Lime
public interface ActionEx5<T0, T1, T2, T3, T4> extends ICallable {
    void invoke(T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) throws Throwable;
    default Action5<T0, T1, T2, T3, T4> throwable() {
        return (val0, val1, val2, val3, val4) -> { try { this.invoke(val0, val1, val2, val3, val4); } catch (Throwable e) { throw new IllegalArgumentException(e); } };
    }
    default Func5<T0, T1, T2, T3, T4, Boolean> optional() {
        return (val0, val1, val2, val3, val4) -> { try { this.invoke(val0, val1, val2, val3, val4); return true; } catch (Throwable e) { return false; } };
    }
    @Override default Object call(Object[] args) { return throwable().call(args); }
}