# https://modmuss50.me/fabric.html
nameSuffix=DYNAMIC
versionMinecraft=DYNAMIC
versionLoader=DYNAMIC
versionFabric=DYNAMIC
versionAdventurePlatform=DYNAMIC

versionLoom=1.17.20
versionMappingIo=0.8.0
overrideJavaVersion=17

versionAdventureApi=FROM_COMMON
versionByteBuddy=FROM_COMMON
versionCommonsLang3=FROM_COMMON
versionGuice = FROM_COMMON
