# https://modmuss50.me/fabric.html
nameSuffix=-26.2
versionMinecraft=26.2
versionLoader=0.19.5
versionFabric=0.161.0+26.2

versionAdventurePlatform=7.1.1
versionAdventureApi=5.2.0
versionCommonsLang3=3.19.0
overrideJavaVersion=25
