package org.lime.system.tuple;

import org.lime.system.execute.*;

// Generated by JavaScript (c) Lime
public class LockTuple7<T0, T1, T2, T3, T4, T5, T6> extends ILockTuple<Tuple7<T0, T1, T2, T3, T4, T5, T6>> {
    public LockTuple7(Tuple7<T0, T1, T2, T3, T4, T5, T6> base) { super(base); }
    public T0 get0() { return (T0)get(0); } public T1 get1() { return (T1)get(1); } public T2 get2() { return (T2)get(2); } public T3 get3() { return (T3)get(3); } public T4 get4() { return (T4)get(4); } public T5 get5() { return (T5)get(5); } public T6 get6() { return (T6)get(6); }
    public void set0(T0 value) { set(0, value); } public void set1(T1 value) { set(1, value); } public void set2(T2 value) { set(2, value); } public void set3(T3 value) { set(3, value); } public void set4(T4 value) { set(4, value); } public void set5(T5 value) { set(5, value); } public void set6(T6 value) { set(6, value); }
    public T0 edit0(Func1<T0, T0> func) { return (T0)edit(0, v -> func.invoke((T0)v)); } public T1 edit1(Func1<T1, T1> func) { return (T1)edit(1, v -> func.invoke((T1)v)); } public T2 edit2(Func1<T2, T2> func) { return (T2)edit(2, v -> func.invoke((T2)v)); } public T3 edit3(Func1<T3, T3> func) { return (T3)edit(3, v -> func.invoke((T3)v)); } public T4 edit4(Func1<T4, T4> func) { return (T4)edit(4, v -> func.invoke((T4)v)); } public T5 edit5(Func1<T5, T5> func) { return (T5)edit(5, v -> func.invoke((T5)v)); } public T6 edit6(Func1<T6, T6> func) { return (T6)edit(6, v -> func.invoke((T6)v)); }
}