package org.lime.core.common.utils.system.execute;

// Generated by JavaScript (c) Lime
public interface ActionEx8<T0, T1, T2, T3, T4, T5, T6, T7> extends Callable {
    void invoke(T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) throws Throwable;
    default Action8<T0, T1, T2, T3, T4, T5, T6, T7> throwable() {
        return (val0, val1, val2, val3, val4, val5, val6, val7) -> { try { this.invoke(val0, val1, val2, val3, val4, val5, val6, val7); } catch (Throwable e) { throw new IllegalArgumentException(e); } };
    }
    default Func8<T0, T1, T2, T3, T4, T5, T6, T7, Boolean> optional() {
        return (val0, val1, val2, val3, val4, val5, val6, val7) -> { try { this.invoke(val0, val1, val2, val3, val4, val5, val6, val7); return true; } catch (Throwable e) { return false; } };
    }
    @Override default Object call(Object[] args) { return throwable().call(args); }
}