package org.lime.core.common.utils.system.execute;

import org.lime.core.common.utils.system.tuple.*;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;

// Generated by JavaScript (c) Lime
public interface Action3<T0, T1, T2> extends Action1<Tuple2<Tuple2<T0,T1>,T2>> {
    void invoke(T0 arg0, T1 arg1, T2 arg2);
    @Override default void invoke(Tuple2<Tuple2<T0,T1>,T2> arg0) { invoke(arg0.val0.val0, arg0.val0.val1, arg0.val1); }
    @Override default Object call(Object[] args) { invoke((T0)args[0], (T1)args[1], (T2)args[2]); return null; }
    static <T0, T1, T2>Action3<T0, T1, T2> of(Method method) {
        return Modifier.isStatic(method.getModifiers()) ?
                (val0, val1, val2) -> Execute.invoke(method, null, new Object[] { val0, val1, val2 }) :
                (val0, val1, val2) -> Execute.invoke(method, val0, new Object[] { val1, val2 });
    }
}