package org.lime.core.common.utils.system.execute;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;

// Generated by JavaScript (c) Lime
public interface Func4<T0, T1, T2, T3, TResult> extends Callable {
    TResult invoke(T0 arg0, T1 arg1, T2 arg2, T3 arg3);
    @Override default Object call(Object[] args) { return invoke((T0)args[0], (T1)args[1], (T2)args[2], (T3)args[3]); }
    static <T0, T1, T2, T3, TResult>Func4<T0, T1, T2, T3, TResult> of(Method method) {
        return Modifier.isStatic(method.getModifiers()) ?
                (val0, val1, val2, val3) -> Execute.invoke(method, null, new Object[] { val0, val1, val2, val3 }) :
                (val0, val1, val2, val3) -> Execute.invoke(method, val0, new Object[] { val1, val2, val3 });
    }
}