package org.lime.core.common.utils.system.execute;

import java.util.Optional;

// Generated by JavaScript (c) Lime
public interface FuncEx9<T0, T1, T2, T3, T4, T5, T6, T7, T8, TResult> extends Callable {
    TResult invoke(T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) throws Throwable;
    default Func9<T0, T1, T2, T3, T4, T5, T6, T7, T8, TResult> throwable() {
        return (val0, val1, val2, val3, val4, val5, val6, val7, val8) -> { try { return this.invoke(val0, val1, val2, val3, val4, val5, val6, val7, val8); } catch (Throwable e) { throw new IllegalArgumentException(e); } };
    }
    default Func9<T0, T1, T2, T3, T4, T5, T6, T7, T8, Optional<TResult>> optional() {
        return (val0, val1, val2, val3, val4, val5, val6, val7, val8) -> { try { return Optional.ofNullable(this.invoke(val0, val1, val2, val3, val4, val5, val6, val7, val8)); } catch (Throwable e) { return Optional.empty(); } };
    }
    @Override default Object call(Object[] args) { return throwable().call(args); }
}