package org.lime.core.common.api.commands.brigadier.exceptions;

import com.mojang.brigadier.ImmutableStringReader;
import com.mojang.brigadier.Message;
import com.mojang.brigadier.exceptions.CommandExceptionType;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import org.lime.core.common.system.execute.Func1;

// Generated by JavaScript (c) Lime
public record Generic1CommandExceptionType<T0>(
        Func1<T0, Message> function)
        implements CommandExceptionType {
    public CommandSyntaxException create(T0 val0) {
        return new CommandSyntaxException(this, function.invoke(val0));
    }
    public CommandSyntaxException createWithContext(T0 val0, ImmutableStringReader reader) {
        return new CommandSyntaxException(this, function.invoke(val0), reader.getString(), reader.getCursor());
    }
}