package org.lime.core.common.api.commands.brigadier.exceptions;

import com.mojang.brigadier.ImmutableStringReader;
import com.mojang.brigadier.Message;
import com.mojang.brigadier.exceptions.CommandExceptionType;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import org.lime.core.common.system.execute.Func7;

// Generated by JavaScript (c) Lime
public record Generic7CommandExceptionType<T0, T1, T2, T3, T4, T5, T6>(
        Func7<T0, T1, T2, T3, T4, T5, T6, Message> function)
        implements CommandExceptionType {
    public CommandSyntaxException create(T0 val0, T1 val1, T2 val2, T3 val3, T4 val4, T5 val5, T6 val6) {
        return new CommandSyntaxException(this, function.invoke(val0, val1, val2, val3, val4, val5, val6));
    }
    public CommandSyntaxException createWithContext(T0 val0, T1 val1, T2 val2, T3 val3, T4 val4, T5 val5, T6 val6, ImmutableStringReader reader) {
        return new CommandSyntaxException(this, function.invoke(val0, val1, val2, val3, val4, val5, val6), reader.getString(), reader.getCursor());
    }
}