package org.lime.core.common.api.commands.brigadier.exceptions;

import com.mojang.brigadier.ImmutableStringReader;
import com.mojang.brigadier.Message;
import com.mojang.brigadier.exceptions.CommandExceptionType;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import org.lime.core.common.utils.system.execute.Func2;

// Generated by JavaScript (c) Lime
public record Generic2CommandExceptionType<T0, T1>(
        Func2<T0, T1, Message> function)
        implements CommandExceptionType {
    public CommandSyntaxException create(T0 val0, T1 val1) {
        return new CommandSyntaxException(this, function.invoke(val0, val1));
    }
    public CommandSyntaxException createWithContext(T0 val0, T1 val1, ImmutableStringReader reader) {
        return new CommandSyntaxException(this, function.invoke(val0, val1), reader.getString(), reader.getCursor());
    }
}