package org.lime.core.common.api.commands.brigadier.exceptions;

import com.mojang.brigadier.ImmutableStringReader;
import com.mojang.brigadier.Message;
import com.mojang.brigadier.exceptions.CommandExceptionType;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import org.lime.core.common.utils.system.execute.Func9;

// Generated by JavaScript (c) Lime
public record Generic9CommandExceptionType<T0, T1, T2, T3, T4, T5, T6, T7, T8>(
        Func9<T0, T1, T2, T3, T4, T5, T6, T7, T8, Message> function)
        implements CommandExceptionType {
    public CommandSyntaxException create(T0 val0, T1 val1, T2 val2, T3 val3, T4 val4, T5 val5, T6 val6, T7 val7, T8 val8) {
        return new CommandSyntaxException(this, function.invoke(val0, val1, val2, val3, val4, val5, val6, val7, val8));
    }
    public CommandSyntaxException createWithContext(T0 val0, T1 val1, T2 val2, T3 val3, T4 val4, T5 val5, T6 val6, T7 val7, T8 val8, ImmutableStringReader reader) {
        return new CommandSyntaxException(this, function.invoke(val0, val1, val2, val3, val4, val5, val6, val7, val8), reader.getString(), reader.getCursor());
    }
}