package org.lime.core.common.utils.execute;

// Generated by JavaScript (c) Lime
public interface ActionEx9<T0, T1, T2, T3, T4, T5, T6, T7, T8> extends Callable {
    void invoke(T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8) throws Throwable;
    default Action9<T0, T1, T2, T3, T4, T5, T6, T7, T8> throwable() {
        return (val0, val1, val2, val3, val4, val5, val6, val7, val8) -> { try { this.invoke(val0, val1, val2, val3, val4, val5, val6, val7, val8); } catch (Throwable e) { throw new IllegalArgumentException(e); } };
    }
    default Func9<T0, T1, T2, T3, T4, T5, T6, T7, T8, Boolean> optional() {
        return (val0, val1, val2, val3, val4, val5, val6, val7, val8) -> { try { this.invoke(val0, val1, val2, val3, val4, val5, val6, val7, val8); return true; } catch (Throwable e) { return false; } };
    }
    @Override default Object call(Object[] args) { return throwable().call(args); }
}