package org.lime.core.common.utils.execute;

import org.lime.core.common.utils.tuple.*;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;

// Generated by JavaScript (c) Lime
public interface Action6<T0, T1, T2, T3, T4, T5> extends Action1<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<T0,T1>,T2>,T3>,T4>,T5>> {
    void invoke(T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);
    @Override default void invoke(Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<T0,T1>,T2>,T3>,T4>,T5> arg0) { invoke(arg0.val0.val0.val0.val0.val0, arg0.val0.val0.val0.val0.val1, arg0.val0.val0.val0.val1, arg0.val0.val0.val1, arg0.val0.val1, arg0.val1); }
    @Override default Object call(Object[] args) { invoke((T0)args[0], (T1)args[1], (T2)args[2], (T3)args[3], (T4)args[4], (T5)args[5]); return null; }
    static <T0, T1, T2, T3, T4, T5>Action6<T0, T1, T2, T3, T4, T5> of(Method method) {
        return Modifier.isStatic(method.getModifiers()) ?
                (val0, val1, val2, val3, val4, val5) -> Execute.invoke(method, null, new Object[] { val0, val1, val2, val3, val4, val5 }) :
                (val0, val1, val2, val3, val4, val5) -> Execute.invoke(method, val0, new Object[] { val1, val2, val3, val4, val5 });
    }
}