package org.lime.core.common.system.tuple;

import org.lime.core.common.system.execute.*;

// Generated by JavaScript (c) Lime
public class LockTuple2<T0, T1> extends BaseLockTuple<Tuple2<T0, T1>> {
    public LockTuple2(Tuple2<T0, T1> base) { super(base); }
    public T0 get0() { return (T0)get(0); } public T1 get1() { return (T1)get(1); }
    public void set0(T0 value) { set(0, value); } public void set1(T1 value) { set(1, value); }
    public T0 edit0(Func1<T0, T0> func) { return (T0)edit(0, v -> func.invoke((T0)v)); } public T1 edit1(Func1<T1, T1> func) { return (T1)edit(1, v -> func.invoke((T1)v)); }
}