name: ${group}.core
version: ${version}
main: org.lime.core.paper.CorePaperPlugin
api-version: 1.13
authors: [Lime]
softdepend: [ProtocolLib]
maven:
  panda-repo: https://repo.panda-lang.org/releases
libraries:
  - net.bytebuddy:byte-buddy-agent:${versionByteBuddy}
  - org.graalvm.js:js:pom:${versionGraalVm}
  - org.graalvm.js:js-scriptengine:${versionGraalVm}
  - org.graalvm.truffle:truffle-api:${versionGraalVm}
  - com.google.inject:guice:${versionGuice}
custom-libraries:
  - dev.rollczi:litecommands-bukkit:${versionLiteCommands}
